/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomenRouteImport } from './routes/women'
import { Route as MenRouteImport } from './routes/men'
import { Route as FashionShowRouteImport } from './routes/fashion-show'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CollectionSs26RouteImport } from './routes/collection-ss26'
import { Route as BoutiquesRouteImport } from './routes/boutiques'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as EnBoutiquesRouteImport } from './routes/en.boutiques'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as CatalogGenderRouteImport } from './routes/catalog.$gender'
import { Route as CatalogGenderSectionRouteImport } from './routes/catalog.$gender_.$section'

const WomenRoute = WomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => rootRouteImport,
} as any)
const MenRoute = MenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionShowRoute = FashionShowRouteImport.update({
  id: '/fashion-show',
  path: '/fashion-show',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSs26Route = CollectionSs26RouteImport.update({
  id: '/collection-ss26',
  path: '/collection-ss26',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiquesRoute = BoutiquesRouteImport.update({
  id: '/boutiques',
  path: '/boutiques',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBoutiquesRoute = EnBoutiquesRouteImport.update({
  id: '/en/boutiques',
  path: '/en/boutiques',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogGenderRoute = CatalogGenderRouteImport.update({
  id: '/catalog/$gender',
  path: '/catalog/$gender',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogGenderSectionRoute = CatalogGenderSectionRouteImport.update({
  id: '/catalog/$gender_/$section',
  path: '/catalog/$gender/$section',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boutiques': typeof BoutiquesRoute
  '/collection-ss26': typeof CollectionSs26Route
  '/contacts': typeof ContactsRoute
  '/fashion-show': typeof FashionShowRoute
  '/men': typeof MenRoute
  '/women': typeof WomenRoute
  '/catalog/$gender': typeof CatalogGenderRoute
  '/en/about': typeof EnAboutRoute
  '/en/boutiques': typeof EnBoutiquesRoute
  '/product/$slug': typeof ProductSlugRoute
  '/en/': typeof EnIndexRoute
  '/catalog/$gender/$section': typeof CatalogGenderSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boutiques': typeof BoutiquesRoute
  '/collection-ss26': typeof CollectionSs26Route
  '/contacts': typeof ContactsRoute
  '/fashion-show': typeof FashionShowRoute
  '/men': typeof MenRoute
  '/women': typeof WomenRoute
  '/catalog/$gender': typeof CatalogGenderRoute
  '/en/about': typeof EnAboutRoute
  '/en/boutiques': typeof EnBoutiquesRoute
  '/product/$slug': typeof ProductSlugRoute
  '/en': typeof EnIndexRoute
  '/catalog/$gender/$section': typeof CatalogGenderSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boutiques': typeof BoutiquesRoute
  '/collection-ss26': typeof CollectionSs26Route
  '/contacts': typeof ContactsRoute
  '/fashion-show': typeof FashionShowRoute
  '/men': typeof MenRoute
  '/women': typeof WomenRoute
  '/catalog/$gender': typeof CatalogGenderRoute
  '/en/about': typeof EnAboutRoute
  '/en/boutiques': typeof EnBoutiquesRoute
  '/product/$slug': typeof ProductSlugRoute
  '/en/': typeof EnIndexRoute
  '/catalog/$gender_/$section': typeof CatalogGenderSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/boutiques'
    | '/collection-ss26'
    | '/contacts'
    | '/fashion-show'
    | '/men'
    | '/women'
    | '/catalog/$gender'
    | '/en/about'
    | '/en/boutiques'
    | '/product/$slug'
    | '/en/'
    | '/catalog/$gender/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/boutiques'
    | '/collection-ss26'
    | '/contacts'
    | '/fashion-show'
    | '/men'
    | '/women'
    | '/catalog/$gender'
    | '/en/about'
    | '/en/boutiques'
    | '/product/$slug'
    | '/en'
    | '/catalog/$gender/$section'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/boutiques'
    | '/collection-ss26'
    | '/contacts'
    | '/fashion-show'
    | '/men'
    | '/women'
    | '/catalog/$gender'
    | '/en/about'
    | '/en/boutiques'
    | '/product/$slug'
    | '/en/'
    | '/catalog/$gender_/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BoutiquesRoute: typeof BoutiquesRoute
  CollectionSs26Route: typeof CollectionSs26Route
  ContactsRoute: typeof ContactsRoute
  FashionShowRoute: typeof FashionShowRoute
  MenRoute: typeof MenRoute
  WomenRoute: typeof WomenRoute
  CatalogGenderRoute: typeof CatalogGenderRoute
  EnAboutRoute: typeof EnAboutRoute
  EnBoutiquesRoute: typeof EnBoutiquesRoute
  ProductSlugRoute: typeof ProductSlugRoute
  EnIndexRoute: typeof EnIndexRoute
  CatalogGenderSectionRoute: typeof CatalogGenderSectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/women': {
      id: '/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men': {
      id: '/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof MenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fashion-show': {
      id: '/fashion-show'
      path: '/fashion-show'
      fullPath: '/fashion-show'
      preLoaderRoute: typeof FashionShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection-ss26': {
      id: '/collection-ss26'
      path: '/collection-ss26'
      fullPath: '/collection-ss26'
      preLoaderRoute: typeof CollectionSs26RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutiques': {
      id: '/boutiques'
      path: '/boutiques'
      fullPath: '/boutiques'
      preLoaderRoute: typeof BoutiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/boutiques': {
      id: '/en/boutiques'
      path: '/en/boutiques'
      fullPath: '/en/boutiques'
      preLoaderRoute: typeof EnBoutiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$gender': {
      id: '/catalog/$gender'
      path: '/catalog/$gender'
      fullPath: '/catalog/$gender'
      preLoaderRoute: typeof CatalogGenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$gender_/$section': {
      id: '/catalog/$gender_/$section'
      path: '/catalog/$gender/$section'
      fullPath: '/catalog/$gender/$section'
      preLoaderRoute: typeof CatalogGenderSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BoutiquesRoute: BoutiquesRoute,
  CollectionSs26Route: CollectionSs26Route,
  ContactsRoute: ContactsRoute,
  FashionShowRoute: FashionShowRoute,
  MenRoute: MenRoute,
  WomenRoute: WomenRoute,
  CatalogGenderRoute: CatalogGenderRoute,
  EnAboutRoute: EnAboutRoute,
  EnBoutiquesRoute: EnBoutiquesRoute,
  ProductSlugRoute: ProductSlugRoute,
  EnIndexRoute: EnIndexRoute,
  CatalogGenderSectionRoute: CatalogGenderSectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
